version: "3.8"

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_test_db
    networks:
      - public-net
      - private-net
    ports:
      - "3307:3306" 
    volumes:
      - mysql-data:/var/lib/mysql
    deploy:
      replicas: 1 

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: root_password
      POSTGRES_DB: my_test_db
    networks:
      - public-net
      - private-net
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    deploy:
      replicas: 1 

  app:
    build:
      context: .
    networks:
      - public-net
      - private-net
    ports:
      - "5000:5000"
    extra_hosts:
      - "mysql_db:172.17.0.1"
      - "pg_db:172.17.0.1"
    depends_on:
      - mysql
      - postgres
    deploy:
      replicas: 2 

networks:
  public-net:
    driver: overlay
  private-net:
    driver: overlay

volumes:
  mysql-data:
  postgres-data:
